on: 
  release:
    types:
      - created

name: build for Openwrt 21.02.3
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Openwrt Package  
    strategy:
      fail-fast: false
      matrix:
        SDK_URL:
        - https://downloads.openwrt.org/releases/21.02.3/targets/bcm47xx/mips74k/openwrt-sdk-21.02.3-bcm47xx-mips74k_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/bcm47xx/generic/openwrt-sdk-21.02.3-bcm47xx-generic_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/bcm47xx/legacy/openwrt-sdk-21.02.3-bcm47xx-legacy_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/bcm4908/generic/openwrt-sdk-21.02.3-bcm4908-generic_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/bcm63xx/generic/openwrt-sdk-21.02.3-bcm63xx-generic_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/ath79/nand/openwrt-sdk-21.02.3-ath79-nand_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/bcm27xx/bcm2708/openwrt-sdk-21.02.3-bcm27xx-bcm2708_gcc-8.4.0_musl_eabi.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/bcm27xx/bcm2709/openwrt-sdk-21.02.3-bcm27xx-bcm2709_gcc-8.4.0_musl_eabi.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/bcm27xx/bcm2710/openwrt-sdk-21.02.3-bcm27xx-bcm2710_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/bcm27xx/bcm2711/openwrt-sdk-21.02.3-bcm27xx-bcm2711_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/sunxi/cortexa53/openwrt-sdk-21.02.3-sunxi-cortexa53_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/sunxi/cortexa8/openwrt-sdk-21.02.3-sunxi-cortexa8_gcc-8.4.0_musl_eabi.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/ramips/mt76x8/openwrt-sdk-21.02.3-ramips-mt76x8_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/ramips/mt7621/openwrt-sdk-21.02.3-ramips-mt7621_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/ramips/mt7620/openwrt-sdk-21.02.3-ramips-mt7620_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/ramips/rt305x/openwrt-sdk-21.02.3-ramips-rt305x_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/bcm53xx/generic/openwrt-sdk-21.02.3-bcm53xx-generic_gcc-8.4.0_musl_eabi.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/ipq40xx/generic/openwrt-sdk-21.02.3-ipq40xx-generic_gcc-8.4.0_musl_eabi.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/ipq806x/generic/openwrt-sdk-21.02.3-ipq806x-generic_gcc-8.4.0_musl_eabi.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/x86/generic/openwrt-sdk-21.02.3-x86-generic_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/x86/64/openwrt-sdk-21.02.3-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz
        - https://downloads.openwrt.org/releases/21.02.3/targets/rockchip/armv8/openwrt-sdk-21.02.3-rockchip-armv8_gcc-8.4.0_musl.Linux-x86_64.tar.xz
    steps:
    
    - name: Checkout - ${{ github.ref }}
      uses: actions/checkout@v3
      
    - name: Install env dependencies
      run: |
        sudo apt update && sudo apt install build-essential gawk flex git gettext libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev -y
    
    - name: TAG
      run: |
          tag_name="${GITHUB_REF##*/}"
          echo Tag $tag_name
          echo "TAG_NAME=${tag_name}" >> $GITHUB_ENV
          
    - name: Download SDK
      env:
        SDK_URL: ${{ matrix.SDK_URL }}
      run: |
        wget -q "${SDK_URL}"
        tar xJf openwrt-sdk-*.tar.xz -C ../
        mv -f "${GITHUB_WORKSPACE}" ../src
        mv ../openwrt-sdk-* "${GITHUB_WORKSPACE}"
        
    - name: Prepare targets
      env:
        REPF: ${{ github.repository }}
      run: |
        REP=$(basename "${REPF}")
        mv -vf ../src "package/${REP}"
        
    - name: Load custom configuration
      env:
        DEBIAN_FRONTEND: noninteractive
        CONFIG_FILE: '.config'
        REPF: ${{ github.repository }}
      run: |
        REP=$(basename "${REPF}")
        [ -e "package/${REP}/${CONFIG_FILE}" ] && mv "${CONFIG}" .config
        make defconfig
           
    - name: Compile Package
      env:
        DEBIAN_FRONTEND: noninteractive
        PKGN: ${{ 'openwrt-vlmcsd' }}
      run: |
        make package/${PKGN}/compile -j$(nproc) V=s
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          draft: true
          name: ${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          files: bin/**/*vlmcsd*.ipk
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
